const { uniq } = require('lodash');
module.exports = uniq([
  // 在以下列表的API会走Mock服务器, 来源参考动态更新的 ./keyList.js
  // 注释掉指定API，将走线上

  'payCheck', // 聚合支付状态轮训检查接口
  'payRequest', // 聚合支付请求接口
  'payRequestWap', // 聚合支付请求WAP接口
  'payRevoke', // 撤销聚合支付接口
  'geturl', // getUrl
  'appList', // 查询应用列表
  'checkstand', // 获取收银台信息
  'list', // 查询企业资产
  'notify', // handlePayNotify
  'return', // handleWapPayReturn
  'commitOrder', // handleMeituanCommitRequest
  'commitOrder', // handleMeituanCommitRequest
  'orderRefund', // handleMeituanRefundRequest
  'validateLoginStatus', // validateLoginStatus
  'asycnLocalTransaction', // asycnLocalTransaction
  'asyncResumeTransaction', // asyncResumeTransaction
  'create', // create
  'eventTest', // eventTest
  'pay', // pay
  'refundNotify', // refundNotify
  'syncTransaction', // syncTransaction
  'addTeamMembers', // 新增AATeam成员
  'agreeJoinTeam', // 同意加入团
  'agreeOpenTeam', // 同意开团
  'createFixedTeam', // 创建固定团
  'createTemporaryTeam', // 创建临时团
  'fixedTeamInfo', // 获取固定团的信息
  'immediateOpenTeam', // 立即开团
  'operatorDepartmentStaffs', // 获取用户同部门员工
  'partTeams', // 我参与的团
  'queryStaffsByKeyword', // 根据关键字查找员工
  'quitTeam', // 退出团
  'reAuditMember', // 重新发起某个成员的审核
  'reCollectMemberMoney', // 重新收取成员的经费
  'refuseJoinTeam', // 拒绝加入团
  'refuseOpenTeam', // 拒绝开团
  'removeMember', // 移除成员
  'removeTeamMembers', // 移除ATeam成员
  'teamStatusCarousel', // 团状态轮播
  'updateTeamFundsInfo', // 修改AATeam经费信息
  'updateTeamIsAudit', // 修改自己被团是否免审核
  'updateTeamMembers', // 更新AATeam成员
  'updateTeamName', // 修改AATeam名称
  'AutoEndConsume', // 自动结束开团
  'collectMoneyResult', // 查询收取团经费结果
  'consumeHistories', // 获取消费历史列表
  'consumeOrderDetail', // 获取某条订单的详情
  'endConsume', // 结束消费
  'CancelTask', // 撤销发放任务
  'CreateImportMatterTask', // 保存导入发放任务
  'CreateManualMatterTask', // 保存手动发放任务
  'CreaterCustomerPlan', // 创建自定义计划
  'CreaterExtraWorkPlan', // 创建加班餐计划
  'DealCustomerTask', // 处理自定义任务
  'DealExtraWorkTask', // 处理加班餐任务
  'GetSnapIdByTask', // 通过任务ID和发放类型获取快照（父对象）
  'RemoveTaskDetail', // 撤销发放明细
  'RevertTask', // 恢复撤销发放任务
  'RevertTaskDetail', // 恢复撤销发放明细
  'RunTaskAllot', // 执行任务积分发放
  'UpdateCustomerPlan', // 更新自定义计划
  'UpdateExtraWorkPlan', // 更新加班餐计划
  'DealAbnormalReportByAdmin', // 管理员处理
  'RevertDealAbnormalReportByAdmin', // 取消管理员处理
  'TenantHasAttendancePermission', // 获取是否拥有假勤权限
  'TimeTask', // 定时任务
  'GetCorpConsume', // 企业账户积分消费明细增加凭证相关列
  'GetAllCorpSubAccounts', // 获取所有企业子账户
  'GetAllCorpSubAccountsAndRecharge', // 获取所有企业子账户和充值名
  'GetRedeemAppList', // 获取应用列表
  'GetRedeemType', // 获取积分类型
  'asset', // 获取个人资产
  'bill', // 获取账单
  'getBillByPage', // 获取账单
  'GetLoginInfo', // 获取登陆信息
  'pointsDetails', // 获取积分详情
  'pointsType', // 获取积分类型
  'HelloWorld', // HelloWorld
  'takeOutExtraWorkRedeem', // 领取加班餐积分
  'AutoRecycle', // 自动回收
  'BatchRecycle', // 批量回收
  'SingleRecycle', // 单个员工回收
  'accountEnable', // 启用账号
  'deleteAllStaffAccount', // 删除全部员工账户
  'GetAllotTaskByStaffRedeemCerId', // 通过员工积分凭证id获取分配任务
  'GetStaffRedeemCerIdByConsumeId', // 根据消费单据ID获取凭证ID
  'GetStaffRedeemOverview', // 员工账户列表增加积分概览列
  'syncStaff', // 同步员工
  'syncStaffByTenantId', // 同步员工
]);
